services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pensionr'
      - 'POSTGRES_PASSWORD=Qk7@4h7Yf'
      - 'POSTGRES_USER=pensionr'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:4.1.3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=Qk7@4h7Yf'
      - 'RABBITMQ_DEFAULT_USER=pensionr'
    ports:
      - '5672:5672'
      - '15672:15672'
